services:
  db:
    image: postgres:15-alpine
    container_name: protos-farm-db
    env_file:
      - .env/.env
    ports:
      - 5430:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: